/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as StylistsRouteImport } from './routes/stylists';
import { Route as ServicesRouteImport } from './routes/services';
import { Route as AuthRouteImport } from './routes/auth';
import { Route as AdminRouteRouteImport } from './routes/admin/route';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as DetailIdRouteImport } from './routes/detail.$id';
import { Route as AdminStylistRouteImport } from './routes/admin/stylist';
import { Route as AdminServicesRouteImport } from './routes/admin/services';
import { Route as AdminReportsRouteImport } from './routes/admin/reports';
import { Route as AuthenticatedMyAppointmentsRouteImport } from './routes/_authenticated/my-appointments';
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated/book';
const StylistsRoute = StylistsRouteImport.update({
    id: '/stylists',
    path: '/stylists',
    getParentRoute: () => rootRouteImport,
});
const ServicesRoute = ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => rootRouteImport,
});
const AdminRouteRoute = AdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRouteRoute,
});
const DetailIdRoute = DetailIdRouteImport.update({
    id: '/detail/$id',
    path: '/detail/$id',
    getParentRoute: () => rootRouteImport,
});
const AdminStylistRoute = AdminStylistRouteImport.update({
    id: '/stylist',
    path: '/stylist',
    getParentRoute: () => AdminRouteRoute,
});
const AdminServicesRoute = AdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AdminRouteRoute,
});
const AdminReportsRoute = AdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AdminRouteRoute,
});
const AuthenticatedMyAppointmentsRoute = AuthenticatedMyAppointmentsRouteImport.update({
    id: '/my-appointments',
    path: '/my-appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedRouteRouteChildren = {
    AuthenticatedBookRoute: AuthenticatedBookRoute,
    AuthenticatedMyAppointmentsRoute: AuthenticatedMyAppointmentsRoute,
};
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);
const AdminRouteRouteChildren = {
    AdminReportsRoute: AdminReportsRoute,
    AdminServicesRoute: AdminServicesRoute,
    AdminStylistRoute: AdminStylistRoute,
    AdminIndexRoute: AdminIndexRoute,
};
const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(AdminRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
    AdminRouteRoute: AdminRouteRouteWithChildren,
    AuthRoute: AuthRoute,
    ServicesRoute: ServicesRoute,
    StylistsRoute: StylistsRoute,
    DetailIdRoute: DetailIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
